language: go

go:
  - 1.13
  - 1.14

os:
  - osx
  - linux
  - windows

addons:
  apt:
    packages:
    - gcc
    - libgtk-3-dev
    - libappindicator3-dev
    - libglib2.0-dev
    - libgtksourceview2.0-dev


script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
